version: '3.1'
services:
  comanage:
    build: .
    container_name: comanage
    domainname: docker
    volumes:
      - bar-metadata:/etc/shibboleth/bar-metadata
      - cm-metadata:/etc/shibboleth/cm-metadata
      - ./data:/data
      - ./conf:/etc/comanage
    environment:
      - DB_PASSWORD
      - DB_HOST=postgres
      - DB_USER=comanage
      - DB_NAME=comanage
      - ADMIN_GIVEN_NAME=Alfred
      - ADMIN_FAMILY_NAME=Wessex
      - ADMIN_USERNAME=admin@bar.ac.uk
    networks:
      - example

  postgres:
    image: postgres
    container_name: comanage-postgres
    domainname: docker
    environment:
      - POSTGRES_USER=comanage
      - POSTGRES_PASSWORD=comanage
      - POSTGRES_DB=comanage
    volumes:
      - comanage-data:/var/lib/postgresql/data
    networks:
      - example

  bar-idp:
    build: bar-idp/
    volumes:
      - bar-metadata:/opt/shibboleth-idp/metadata/
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    container_name: bar-idp
    stop_signal: RTMIN+3
    environment:
      - container=docker
    tmpfs:
      - /run
      - /tmp
    cap_add:
      - SYS_ADMIN
    expose:
      - "8080"
      - "8443"
    networks:
      - example

  bar-kdc:
    build: bar-kdc/
    container_name: bar-kdc
    networks:
      - example

  cm-idp:
    build: cm-idp/
    volumes:
      - cm-metadata:/opt/shibboleth-idp/metadata/
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    container_name: cm-idp
    stop_signal: RTMIN+3
    environment:
      - container=docker
    tmpfs:
      - /run
      - /tmp
    cap_add:
      - SYS_ADMIN
    expose:
      - "8080"
      - "8443"
    networks:
      - example

  cm-kdc:
    build: cm-kdc/
    container_name: cm-kdc
    networks:
      - example


volumes:
  comanage-data: {}
  bar-metadata:
  cm-metadata:

networks:
  example:

